import {  Montserrat, Space_Grotesk } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })
const space_grotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space-grotesk'})

export const metadata = {
  title: 'Hack the Jobs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${space_grotesk.variable}`}>{children}</body>
    </html>
  )
}
