name: Hack The Jobs CICD

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set NODE_ENV
        run: echo "NODE_ENV=development" >> .env
        if: github.ref == 'refs/heads/development'
           
      - name: Set NODE_ENV
        run: echo "NODE_ENV=production" >> .env
        if: github.ref == 'refs/heads/main'
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Slack Notification - Deployment Initiated
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Starting deployment :hourglass_flowing_sand: commit: ${{ github.event.head_commit.message }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Deployment Success
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ success() }}
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Success :rocket: commit: ${{ github.event.head_commit.message }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Deployment Failed
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ failure() }}
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Failed deployment :x: commit: ${{ github.event.head_commit.message }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
